spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/student
    username: tatsuki
    password: Tatsuki07
server:
 servlet:
  context-path: /ex-beginner